add std:: in front of array
fixes the following error, which results when Intel 15 is used.

[ 31%] Building CXX object CMakeFiles/El.dir/src/blas_like/level1-C.cpp.o
In file included from /tmp/jeff/include/El/core.hpp(119),
                 from /tmp/jeff/include/El.hpp(18),
                 from /global/project/projectdirs/m1907/Elemental/src/blas_like/level1-C.cpp(9):
/tmp/jeff/include/El/core/imports/scalapack.hpp(29): error: a class or namespace qualified name is required
  typedef typename array<int,9> Desc;
                   ^

compilation aborted for /global/project/projectdirs/m1907/Elemental/src/blas_like/level1-C.cpp (code 2)
make[2]: *** [CMakeFiles/El.dir/src/blas_like/level1-C.cpp.o] Error 2
make[1]: *** [CMakeFiles/El.dir/all] Error 2
make: *** [all] Error 2